version: "3.9"

x-base-service: &base-service
    image: netfoundry/ziti-edge-tunnel:latest # https://hub.docker.com/repository/docker/netfoundry/ziti-edge-tunnel/tags?page=1&ordering=last_updated
    devices:
    - /dev/net/tun:/dev/net/tun
    volumes:
    - .:/ziti-edge-tunnel
    - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
    environment:
    - NF_REG_NAME            # inherit when run like this: NF_REG_NAME=AcmeIdentity docker-compose up ziti-tun
    network_mode: host       # use the Docker host's network, not the Docker bridge
    privileged: true

services:
    ziti-tun:                # tunneler for one Ziti identity
        <<: *base-service
        command: 
        - --verbose=4
        - --dns-ip-range=100.64.64.0/18
    ziti-tun-dir:             # tunneler for all identities in /ziti-edge-tunnel
        <<: *base-service
        command:
        - --verbose=4
        - --dns-ip-range=100.64.64.0/18
        environment: []      # ignore NF_REG_NAME and load all identities in same dir
    ziti-test:               # docker-compose exec ziti-test bash
        <<: *base-service
        entrypoint: ["sh", "-c", "while true; do sleep infinity; done"]
    ziti-host:                # tunneler for hosting services without providing DNS or IP routes
        image: netfoundry/ziti-edge-tunnel:latest
        volumes:
        - .:/ziti-edge-tunnel
        environment:
        - NF_REG_NAME            # inherit when run like this: NF_REG_NAME=AcmeIdentity docker-compose up ziti-tun
        network_mode: bridge     # use the Compose project's Docker bridge network
        privileged: false        # will fail to provide DNS and IP routes if not privileged
        command: 
        - --verbose=4
        - --dns-ip-range=100.64.64.0/18
